import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtemp, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { setTimeout as delay } from "node:timers/promises";

const project = fileURLToPath(new URL("../", import.meta.url));
const root = await mkdtemp(join(tmpdir(), "pi-dag-tui-"));
const evidence = resolve(project, "artifacts/tui");
await mkdir(evidence, { recursive: true });
const run = (...args) => {
  const result = spawnSync("tmux", args, { encoding: "utf8", timeout: 5000 });
  if (result.status !== 0) throw new Error(`tmux ${args.join(" ")}: ${result.stderr}`);
  return result.stdout.trimEnd();
};
const exists = spawnSync("tmux", ["has-session", "-t", "=Test"], { encoding: "utf8" }).status === 0;
const name = `dag-m1-${Date.now().toString(36)}`;
const pane = exists ? run("new-window", "-d", "-t", "Test", "-n", name, "-P", "-F", "#{pane_id}") : run("new-session", "-d", "-s", "Test", "-n", name, "-x", "120", "-y", "36", "-P", "-F", "#{pane_id}");
const window = run("display-message", "-p", "-t", pane, "#{window_id}");
run("set-option", "-w", "-t", window, "window-size", "manual");
run("resize-window", "-t", window, "-x", "120", "-y", "36");
const capture = () => run("capture-pane", "-p", "-t", pane);
const info = () => run("display-message", "-p", "-t", pane, "session=#{session_name} window=#{window_name} pane=#{pane_id} size=#{pane_width}x#{pane_height} command=#{pane_current_command} dead=#{pane_dead}");
const send = (text) => { run("send-keys", "-t", pane, "-l", text); run("send-keys", "-t", pane, "Enter"); };
const poll = async (predicate, label, timeout = 20000) => {
  const deadline = Date.now() + timeout;
  while (Date.now() < deadline) {
    if (await predicate()) return;
    await delay(100);
  }
  await writeFile(join(evidence, "failure.txt"), `${info()}\n${capture()}`);
  throw new Error(`等待失败：${label}; evidence=${evidence}`);
};
const ledger = async () => {
  const files = (await readdir(join(root, "sessions"))).filter((file) => file.endsWith(".jsonl"));
  assert.equal(files.length, 1);
  return (await readFile(join(root, "sessions", files[0]), "utf8")).trim().split("\n").map((line) => JSON.parse(line));
};
const snapshot = async () => (await ledger()).findLast((entry) => entry.type === "custom" && entry.customType === "pi-dag-workflow.state")?.data;
const checks = [];
const save = async (label) => {
  await delay(200);
  const text = capture();
  assert.doesNotMatch(text, /Error loading extension|rendered line.*exceed|Unhandled|TypeError|SyntaxError/i);
  const details = info();
  assert.match(details, /dead=0/);
  await writeFile(join(evidence, `${label}.txt`), `${details}\n\n${text}\n`);
  checks.push({ label, window: details });
};
const quoted = (text) => `'${text.replaceAll("'", "'\\''")}'`;
const args = [process.execPath, join(project, "node_modules/@earendil-works/pi-coding-agent/dist/bundle/cli.js"), "--offline", "--no-extensions", "--no-skills", "--no-prompt-templates", "--no-themes", "--no-context-files", "--no-approve", "--session-id", "m1-tui", "--provider", "dag-test", "--model", "scripted", "-e", project, "-e", join(project, "test/fixtures/offline-model.ts")];
const launch = `cd ${quoted(root)} && env -i HOME=${quoted(root)} PATH=${quoted(process.env.PATH ?? "")} TERM=xterm-256color LANGUAGE=zh-CN PI_OFFLINE=1 PI_CODING_AGENT_DIR=${quoted(join(root, "agent"))} PI_CODING_AGENT_SESSION_DIR=${quoted(join(root, "sessions"))} ${args.map(quoted).join(" ")}`;

try {
  send(launch);
  await poll(() => info().includes("command=pi") && capture().includes("escape interrupt") && capture().includes("0.0%/") && capture().includes("scripted"), "Pi 启动并完成编辑器绘制");
  await delay(500);
  await save("01-startup");
  send("帮我创建两件待办：检查入口，然后汇总结果，第二件依赖第一件。");
  await poll(async () => { try { return (await snapshot())?.tasks.length === 2 && capture().includes("汇总结果") && capture().includes("#2"); } catch { return false; } }, "自然语言与工具创建两项 Todo");
  await save("02-natural-todos");
  send("/todos start #2");
  await poll(() => capture().includes("前置未完成"), "依赖阻止开始");
  assert.equal((await snapshot()).tasks[1].status, "pending");
  await save("03-dependency-blocked");
  send("/plan start");
  await poll(async () => (await snapshot()).plan && capture().includes("只读"), "进入 Plan");
  await save("04-plan-readonly");
  send("请把第一项标为完成");
  await poll(() => capture().includes("不允许开始或完成"), "Plan 禁止完成");
  assert.equal((await snapshot()).tasks[0].status, "pending");
  await save("05-plan-completion-denied");
  send("请写入测试文件");
  await poll(() => capture().includes("不允许执行 write"), "Plan 禁止写入");
  assert.ok(!(await readdir(root)).includes("should-not-exist.txt"));
  send("!touch forbidden-shell.txt");
  await poll(() => capture().includes("执行 shell 需先"), "Plan 禁止用户 shell");
  assert.ok(!(await readdir(root)).includes("forbidden-shell.txt"));
  await save("06-write-and-shell-denied");
  send("/todos edit #2 规划后的汇总");
  await poll(async () => (await snapshot()).tasks[1].subject === "规划后的汇总", "Plan 编辑同一清单");
  send("/todos");
  await poll(() => capture().includes("Esc 返回"), "Todos 详情");
  assert.equal((capture().match(/Todo \(0\/2\)/g) ?? []).length, 1, "detail view must not duplicate the widget");
  await save("07-todos-panel");
  run("send-keys", "-t", pane, "Escape");
  await delay(300);
  send("/dag");
  await poll(() => capture().includes("DAG") && /[┌┐└┘┬─]/.test(capture()), "派生 DAG 实线图");
  await save("08-dag-panel");
  run("send-keys", "-t", pane, "Escape");
  await delay(300);
  run("resize-window", "-t", window, "-x", "40", "-y", "22");
  await poll(() => info().includes("size=40x22") && capture().includes("Todo"), "窄终端重绘");
  await save("09-narrow-40-columns");
  run("resize-window", "-t", window, "-x", "120", "-y", "36");
  await delay(300);
  send("/plan off");
  await poll(async () => !(await snapshot()).plan, "退出 Plan");
  send("请把第一项标为完成");
  await poll(async () => (await snapshot()).tasks[0].status === "completed", "正常模式允许完成");
  await save("10-normal-completion");
  send("/todos hide");
  await poll(async () => !(await snapshot()).visible, "隐藏小组件");
  await save("11-hidden-widget");
  send("/todos show");
  await poll(async () => (await snapshot()).visible, "显示小组件");
  send("/plan start");
  await poll(async () => (await snapshot()).plan, "保存 Plan 用于恢复");
  const before = await snapshot();
  const assistantCount = (await ledger()).filter((entry) => entry.type === "message" && entry.message?.role === "assistant").length;
  run("send-keys", "-t", pane, "C-d");
  await poll(() => !info().includes("command=pi") && !info().includes("command=node"), "退出 Pi");
  send(launch);
  await poll(() => info().includes("command=pi") && capture().includes("scripted") && capture().includes("Plan") && capture().includes("规划后的汇总"), "重启恢复");
  assert.deepEqual(await snapshot(), before);
  assert.equal((await ledger()).filter((entry) => entry.type === "message" && entry.message?.role === "assistant").length, assistantCount);
  await save("12-restart-restored-no-model-turn");
  const summary = { passed: true, provider: "offline scripted fixture; not a real LLM", enabledExtensions: [project, join(project, "test/fixtures/offline-model.ts")], root, pane, window, tmuxSession: "Test", checks };
  await writeFile(join(evidence, "summary.json"), JSON.stringify(summary, null, 2) + "\n");
  run("select-window", "-t", window);
  console.log(`PASS: ${checks.length} real TUI captures; ${info()}\nEvidence: ${evidence}\nTest data: ${root}\nPane left open for manual inspection; no other tmux window was modified.`);
} catch (error) {
  await writeFile(join(evidence, "failure.txt"), `${info()}\n${capture()}\n\n${String(error)}`);
  console.error(`FAIL: ${error}; pane ${pane} left open; evidence ${evidence}`);
  process.exitCode = 1;
}
